### PR TITLE
Add square barckets to evaluator regex

### PR DESCRIPTION
**Pull request by gunnar-enerin**
Resolves issue #247 

A minor fix to enable the possibility of having event contexts passed through nested repeater objects where the child repeater object is the item of a parent repeater.

### CODE REVIEW

**Comment by ramedina86** [comment]
Thanks @gunnar-enerin for your contribution!

@FabienArcellier I think you've looked into this, do you have any input?

**Comment by ramedina86** [comment]
Hey @mmikita95 since you already looked into this, can you provide your input? Also, let me know if you think we require any changes to our tests to avoid running into the issue that op detected.

**Comment by mmikita95** [comment]
@ramedina86 good point about 
tests, I think we would definitely need it here. 

@gunnar-enerin could you please share your case that was triggering an error with a little more detail? I tried to reproduce it locally based on your description (my bad not doing it the first time and relying on code inspection solely 😅), and it avoids me for some reason – maybe I misunderstood something.

**Comment by gunnar-enerin** [comment]
Hi, I should probably have added a concrete example initially as well, but I didn't have much time and wanted to get it out there. Sorry if that has caused extra work for you guys. 

It turns out (obviously in retrospect) that it has nothing in particular to do with nested repeaters, only using square brackets in the specification of the repeater object. Here is a minimal example that recreates the bug: https://github.com/gunnar-enerin/square-brackets-streamsync-bug-example.git 

The example is just a repeater object containing a section with a button inside where the repeater object is specified using square brackets notation (necessary when using dynamic specification, for instance when using nested repeaters, but not actually necessary in this case). Pressing the button causes a runtime error due to the regex not allowing square brackets.

**Comment by ramedina86** [comment]
We've looked into this in detail @gunnar-enerin 

It's indeed a much needed fix. Thanks for spotting the issue and providing the fix!

It's quite impressive that you managed to get into the depths of Streamsync.

Hope to hear from you in the future!

**Pull request merged**
